# Generated by Django 4.2.8 on 2023-12-09 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=25)),
                ('fecha_de_creacion', models.DateTimeField(default=datetime.datetime(2023, 12, 9, 12, 24, 48, 420293))),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to='recetas')),
            ],
        ),
    ]
