# Generated by Django 4.2.8 on 2023-12-10 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='fecha_de_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 0, 17, 11, 869995)),
        ),
    ]
