# Generated by Django 4.2.8 on 2023-12-11 01:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_alter_receta_fecha_de_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='fecha_de_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 22, 53, 28, 899059)),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Principal.receta')),
            ],
            options={
                'ordering': ['-fechaComentario'],
            },
        ),
    ]
