# Generated by Django 4.2.8 on 2023-12-11 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_alter_receta_fecha_de_creacion_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='autor',
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_de_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 19, 11, 51, 630263)),
        ),
    ]
